version: '3'
services:
  web:
    build: ./TutorialUniversity/
    ports:
     - "8080:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
      ConnectionStrings__DefaultConnection: 'User ID=postgres;Password=qwe123;Host=db;Port=5432;Database=TutorialUniversity3;Pooling=true;'
    networks: 
      - tutorial_university_network
  db:
    build: ./postgres_db_docker/
    environment:
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: TutorialUniversity3
    networks: 
      - tutorial_university_network
networks:
  tutorial_university_network:

#command to initialize database (execute after "docker-compose up", after that do "docker-compose restart") 
#docker run -it --rm -v "$(pwd):/app" --workdir /app --network=tutorialuniversity_tutorial_university_network -e ConnectionStrings__DefaultConnection="User ID=postgres;Password=qwe123;Host=db;Port=5432;Database=TutorialUniversity3;Pooling=true;" microsoft/aspnetcore-build /bin/bash -c "dotnet restore && dotnet ef database update"
